services:
    wordpress:
        image: wordpress:latest
        volumes:
            - wp_data:/var/www/html
        ports:
            - 8080:80
        restart: unless-stopped
        depends_on:
            - db
        env_file: .env
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        networks:
            - wp_network

    db:
        image: mariadb:latest
        command: '--default-authentication-plugin=mysql_native_password'
        volumes:
            - db_data:/var/lib/mysql
        restart: unless-stopped
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        expose:
            - 3306
            - 33060
        networks:
            - wp_network

volumes:
    db_data:
    wp_data:

networks:
    wp_network:
        driver: bridge
